name: Create release with Maven

on:
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
        check-latest: false
        cache: maven

    - name: Package
      run: mvn package

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: minor

    - name: Rename artifact with version
      run: cp "target/ColonyManagement.jar" "target/ColonyManagement-${{ steps.tag_version.outputs.new_tag }}.jar"

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/ColonyManagement-${{ steps.tag_version.outputs.new_tag }}.jar
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}