name: Run Tests With Maven

on:
  push:
    branches:    
      - master
  pull_request:
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
        check-latest: false
        cache: maven

    - name: Build and Test
      run: mvn test